# -*- coding: utf-8 -*-
"""pipeline_vqvae-transformer-classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VsormjXMQZZ7KsqY8Gj9GcaCKT3RCiLR

# Set Up Modules
"""
# =============================================================================
# import sys
# sys.path.insert(0, '/local/altamabp')
# =============================================================================
# =============================================================================
# import os, sys, importlib.util, site, pathlib
# print("Python:", sys.executable)
# print("CWD   :", os.getcwd())
# print("Top sys.path entries:")
# for p in sys.path[:10]:
#     print("  ", p)
# print("vqvae spec:", importlib.util.find_spec("vqvae"))
# print("site-packages:", site.getsitepackages() if hasattr(site, "getsitepackages") else [])
# print("User site:", site.getusersitepackages() if hasattr(site, "getusersitepackages") else "")
# 
# # Optional: list files in CWD so we see what's there
# print("\nFiles here:")
# for p in pathlib.Path(".").glob("*"):
#     print("  ", p)
# 
# 
# =============================================================================



import argparse, json, math, os, random, sys, re
import numpy as np
import matplotlib.pyplot as plt
import torch
from torch import nn, optim
from torch.utils.data import DataLoader, Dataset, Subset, ConcatDataset
from torchvision import datasets, transforms, utils
from torchvision.models import resnet50, ResNet50_Weights
from torch.utils.tensorboard import SummaryWriter
from torchsummary import summary
from torch.optim.lr_scheduler import CyclicLR
from sklearn.model_selection import train_test_split
from tqdm import tqdm
from vqvae import FlatVQVAE
import torch.distributed as dist
import neptune.new as neptune
from transformers import DistilBertForMaskedLM, DistilBertConfig
from PIL import Image




def ddp_ready() -> bool:
    return dist.is_available() and dist.is_initialized()

def init_ddp_from_env():
    """
    Initialize torch.distributed only if launched with torchrun (env://).
    Safe no-op on single-GPU runs.
    """
    if not dist.is_available() or dist.is_initialized():
        return
    if ("RANK" in os.environ) or ("WORLD_SIZE" in os.environ) or ("LOCAL_RANK" in os.environ):
        backend = "nccl" if torch.cuda.is_available() else "gloo"
        dist.init_process_group(backend=backend, init_method="env://")
        if torch.cuda.is_available():
            torch.cuda.set_device(int(os.environ.get("LOCAL_RANK", 0)))


#def is_primary() -> bool:
    # True on single-GPU runs and on rank 0 when using DDP
#    return (not dist.is_available()) or (not dist.is_initialized()) or dist.get_rank() == 0



"""# Train VQ_VAE

> set up Logging
"""

run = neptune.init_run(
    project="UTKFaces",
    api_token="eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmUuYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS5haSIsImFwaV9rZXkiOiIwMmExYTliOC1mYjkyLTQ4M2YtYjFiYS1iZWQ1Y2E0OTJlNTkifQ==",
    capture_stdout=False,
    capture_stderr=False,
    source_files=["pipeline_vqvae_transformer_classification.py"]
)

"""> Define a custom Dataset"""


class CustomImageDataset(Dataset):
    def __init__(self, image_dir, transform=None):
        self.image_dir = image_dir
        self.transform = transform
        self.image_files = [f for f in os.listdir(image_dir) if f.endswith('.png')]
        # Regex: first number, anything, last digit before .png
        self.pattern = re.compile(r'^(\d+)_.*_(\d)\.png$')

    def __len__(self):
        return len(self.image_files)

    def __getitem__(self, idx):
        img_name = self.image_files[idx]
        img_path = os.path.join(self.image_dir, img_name)
        image = Image.open(img_path).convert('RGB')

        # Extract only the last digit from the filename
        m = self.pattern.match(img_name)
        if not m:
            raise ValueError(f"Filename {img_name} does not match expected pattern.")
        last_digit = m.group(2)          # group(2) is the last digit
        label = int(last_digit)          # convert it to int (0-9)

        if self.transform:
            image = self.transform(image)
        return image, label


"""> Set Up train function"""



#def _ddp_initialized():
#    return dist.is_available() and dist.is_initialized()

def ddp_initialized() -> bool:
    return dist.is_available() and dist.is_initialized()

def is_primary() -> bool:
    # True for single-GPU / non-DDP runs, or rank 0 in DDP
    if not ddp_initialized():
        return True
    try:
        return dist.get_rank() == 0
    except Exception:
        # If something weird happens before init, default to primary
        return True

# =============================================================================
# def train(epoch, loader, model, optimizer, scheduler, device, val_loader=None):
#     # progress bar only on primary
#     iterator = tqdm(loader) if is_primary() else loader
# 
#     criterion = nn.MSELoss()
#     latent_loss_weight = 0.35
#     diversity_loss_weight = 0.0001
# 
#     # running sums for epoch-average (global, across ranks)
#     mse_sum = 0.0
#     mse_n = 0.0
# 
#     model.train()  # ALL ranks
# 
#     for i, (img, label) in enumerate(iterator):
#         img = img.to(device, non_blocking=True)
# 
#         optimizer.zero_grad(set_to_none=True)
# 
#         out, latent_loss, diversity_loss, codebook_usage = model(img)
#         recon_loss = criterion(out, img)
#         latent_loss = latent_loss.mean()
# 
#         loss = recon_loss + latent_loss_weight * latent_loss + diversity_loss_weight * diversity_loss
#         loss.backward()
#         optimizer.step()
#         if scheduler is not None:
#             scheduler.step()
# 
#         # ---- distribute this batch's contribution (sum over samples) ----
#         batch_size = img.shape[0]
#         sum_t = torch.tensor(recon_loss.item() * batch_size, device=device, dtype=torch.float64)
#         n_t   = torch.tensor(batch_size,                  device=device, dtype=torch.float64)
# 
#         if ddp_initialized():
#             dist.all_reduce(sum_t, op=dist.ReduceOp.SUM)
#             dist.all_reduce(n_t,   op=dist.ReduceOp.SUM)
# 
#         # update running epoch totals with GLOBAL contributions
#         mse_sum += float(sum_t.item())
#         mse_n   += float(n_t.item())
#         avg_mse = mse_sum / max(1.0, mse_n)
# 
#         if is_primary():
#             lr = optimizer.param_groups[0]["lr"]
#             iterator.set_description(
#                 f"epoch: {epoch + 1}; mse: {recon_loss.item():.5f}; "
#                 f"latent: {latent_loss.item():.3f}; avg mse: {avg_mse:.5f}; lr: {lr:.5f}"
#             )
#             run["vqvae/train-mse"].log(recon_loss.item())
#             run["vqvae/train-latent"].log(latent_loss.item())
#             run["vqvae/train-epoch"].log(epoch + 1)
#             # if codebook_usage is a tensor, log its scalar value
#             if isinstance(codebook_usage, torch.Tensor) and codebook_usage.numel() == 1:
#                 run["vqvae/train-num_used_codebooks"].log(codebook_usage.item())
#             else:
#                 run["vqvae/train-num_used_codebooks"].log(float(codebook_usage))
# 
#     # ----- Validation pass (optional) -----
#     if val_loader is not None:
#         model.eval()  # ALL ranks
# 
#         val_mse_sum = 0.0
#         val_mse_n = 0.0
# 
#         vloader = tqdm(val_loader, leave=False, desc="validating") if is_primary() else val_loader
# 
#         with torch.no_grad():
#             for img, _ in vloader:
#                 img = img.to(device, non_blocking=True)
#                 out, _, _, _ = model(img)
#                 recon_loss = criterion(out, img)
# 
#                 batch_size = img.shape[0]
#                 sum_t = torch.tensor(recon_loss.item() * batch_size, device=device, dtype=torch.float64)
#                 n_t   = torch.tensor(batch_size,                  device=device, dtype=torch.float64)
# 
#                 if ddp_initialized():
#                     dist.all_reduce(sum_t, op=dist.ReduceOp.SUM)
#                     dist.all_reduce(n_t,   op=dist.ReduceOp.SUM)
# 
#                 val_mse_sum += float(sum_t.item())
#                 val_mse_n   += float(n_t.item())
# 
#                 if is_primary():
#                     run["vqvae/val-mse_batch"].log(recon_loss.item())
# 
#         if is_primary():
#             val_mse_avg = val_mse_sum / max(1.0, val_mse_n)
#             run["vqvae/val-mse"].log(val_mse_avg)
#             run["vqvae/val-epoch"].log(epoch + 1)
# 
#         model.train()  # resume train mode
# =============================================================================

def train(epoch, loader, model, optimizer, scheduler, device, val_loader=None):
    if is_primary():
        loader = tqdm(loader)

    criterion = nn.MSELoss()

    latent_loss_weight = 0.35
    diversity_loss_weight = 0.0001

    mse_sum = 0
    mse_n = 0
    model.train()
    for i, (img, label) in enumerate(loader):
        model.zero_grad()

        img = img.to(device)
        out, latent_loss, diversity_loss, codebook_usage = model(img)
        recon_loss = criterion(out, img)
        latent_loss = latent_loss.mean()
        loss = recon_loss + latent_loss_weight * latent_loss + diversity_loss_weight * diversity_loss
        loss.backward()

        if scheduler is not None:
            scheduler.step()
        optimizer.step()

        part_mse_sum = recon_loss.item() * img.shape[0]
        part_mse_n = img.shape[0]
        comm = {"mse_sum": part_mse_sum, "mse_n": part_mse_n}
        comm = dist.all_gather(comm)

        for part in comm:
            mse_sum += part["mse_sum"]
            mse_n += part["mse_n"]

        if is_primary():
            lr = optimizer.param_groups[0]["lr"]
            loader.set_description(
                (
                    f"epoch: {epoch + 1}; mse: {recon_loss.item():.5f}; "
                    f"latent: {latent_loss.item():.3f}; avg mse: {mse_sum / mse_n:.5f}; "
                    f"lr: {lr:.5f}"
                )
            )
            run["vqvae/train-mse"].log(recon_loss.item())
            run["vqvae/train-latent"].log(latent_loss.item())
            run["vqvae/train-epoch"].log(epoch + 1)
            run["vqvae/train-num_used_codebooks"].log(codebook_usage)

    # ----- Validation pass (optional) -----
    if val_loader is not None:
        model.eval()
        val_mse_sum = 0
        val_mse_n = 0

        vloader = val_loader
        if is_primary():
            vloader = tqdm(val_loader, leave=False, desc="validating")

        with torch.no_grad():
            for img, _ in vloader:
                img = img.to(device)
                out, _, _, _ = model(img)
                recon_loss = criterion(out, img)

                part_mse_sum = recon_loss.item() * img.shape[0]
                part_mse_n = img.shape[0]
                comm = {"mse_sum": part_mse_sum, "mse_n": part_mse_n}
                comm = dist.all_gather(comm)

                for part in comm:
                    val_mse_sum += part["mse_sum"]
                    val_mse_n += part["mse_n"]

                if is_primary():
                    run["vqvae/val-mse_batch"].log(recon_loss.item())

        if is_primary():
            val_mse_avg = val_mse_sum / max(1, val_mse_n)
            run["vqvae/val-mse"].log(val_mse_avg)
            run["vqvae/val-epoch"].log(epoch + 1)

        model.train()


"""> Parse essential arguments"""

parser = argparse.ArgumentParser()
parser.add_argument("--n_gpu", type=int, default=1)

port = (
    2 ** 15
    + 2 ** 14
    + hash(os.getuid() if sys.platform != "win32" else 1) % 2 ** 14
)
parser.add_argument("--dist_url", default=f"tcp://127.0.0.1:{port}")
parser.add_argument("--save_path_models", default="/local/altamabp/checkpoint/vqvae/")
parser.add_argument("--size", type=int, default=80)
parser.add_argument("--epoch", type=int, default=100)
parser.add_argument("--lr", type=float, default=1e-4)
parser.add_argument("--sched", type=str)

##--train_vqvae --train_classifier --train_transformer
parser.add_argument("--train_vqvae", action="store_true", help="Train VQ-VAE instead of loading checkpoint")
parser.add_argument("--train_classifier", action="store_true", help="Train classifier instead of loading checkpoint")
parser.add_argument("--train_transformer", action="store_true", help="Train transformer instead of loading checkpoint")

parser.add_argument("--classifier_ckpt", type=str, default="/local/altamabp/checkpoint/classifier/resnet50/weights_epoch100_fullTrain.pth", help="Path to classifier checkpoint")

parser.add_argument(
    "--ckpt_distil_combined",
    type=str,
    default="/local/altamabp/checkpoint/distil/80x80_100ClassImagenet_flat_144x456codebook_75mask_epoch100_fullTrain.pt",
    help="Path to combined distillation checkpoint"
)
parser.add_argument(
    "--ckpt_vqvae",
    type=str,
    default="/local/altamabp/checkpoint/vqvae/model_epoch100_flat_vqvae80x80_144x456codebook_fullTrain.pth",
    help="Path to trained VQ-VAE checkpoint"
)


# args = parser.parse_args()
args, unknown = parser.parse_known_args()

torch.cuda.set_device(3)  # Use GPU 1 (if desired)
torch.cuda.empty_cache()
device = "cuda" if torch.cuda.is_available() else "cpu"


# Initialize DDP if launched with torchrun; otherwise stays single-process
init_ddp_from_env()

# SAFE flag: only True if torch.distributed is initialized
args.distributed = (dist.is_available() and dist.is_initialized() and dist.get_world_size() > 1)


transform = transforms.Compose(
    [
        transforms.Resize((80,80)),
        transforms.Lambda(lambda x: x if isinstance(x, (bytes, bytearray)) else x),  # placeholder if needed
        transforms.ToTensor(),                             # PIL/uint8 → [0,1]
        transforms.Lambda(lambda t: t.clamp(0, 1)),  
    ]
)

dataset = CustomImageDataset('/local/altamabp/UTKFace_dataset_subset_150000', transform=transform)
data_loader = DataLoader(dataset, batch_size=16 // args.n_gpu, shuffle=False, num_workers=12)

dataset_val = CustomImageDataset('/local/altamabp/UTKFace_dataset_subset_10000', transform=transform)
data_loader_val = DataLoader(dataset, batch_size=16 // args.n_gpu, shuffle=False, num_workers=12)


print(len(dataset))
print(len(dataset[0]))
print(dataset[0][0].shape)

model = FlatVQVAE().to(device)


if args.distributed:
    model = nn.parallel.DistributedDataParallel(
        model,
        device_ids=[dist.get_local_rank()],
        output_device=dist.get_local_rank(),
    )

optimizer = optim.Adam(model.parameters(), lr=args.lr)
run["train/lr"].log(args.lr)
scheduler = None
if args.sched == "cycle":
    scheduler = CyclicLR(
    optimizer,
    base_lr=args.lr * 0.1,
    max_lr=args.lr,
    step_size_up=len(data_loader) * args.epoch * 0.05,
    mode="triangular",
    cycle_momentum=False)
x=0


if args.train_vqvae:
    print("Training VQ-VAE...")
    for i in range(args.epoch):
        train(i, data_loader, model, optimizer, scheduler, device, data_loader_val)
        x=i
        if is_primary():
            model_path = os.path.join(args.save_path_models, f"model_epoch{i+1}_flat_vqvae80x80_144x456codebook.pth")
            torch.save(model.state_dict(), model_path)
else:
    print(f"Loading VQ-VAE from {args.ckpt_vqvae}")
    model.load_state_dict(torch.load(args.ckpt_vqvae, map_location=device))
    model.eval()
    
    
"""# Reconstruction Step

- Reconstruct Images
- Save Codebook
- Save Latent Space - Indices
- Save labels properly
"""


parser.add_argument("--save_path_imgs", default="/local/altamabp/image/reconstruction_fullTrain/")

args, unknown = parser.parse_known_args()


torch.cuda.set_device(3)  # Use GPU 1 (if desired)
torch.cuda.empty_cache()
device = "cuda" if torch.cuda.is_available() else "cpu"

# Initialize DDP if launched with torchrun; otherwise stays single-process
init_ddp_from_env()

# SAFE distributed flag (won’t throw if not initialized)
args.distributed = ddp_ready() and (dist.get_world_size() > 1)

model_vqvae = FlatVQVAE().to(device)
model_vqvae.load_state_dict(torch.load(args.ckpt_vqvae, map_location=device))
model_vqvae = model_vqvae.to(device)
model_vqvae.eval()
epoch = args.epoch

if args.distributed:
    model_vqvae = nn.parallel.DistributedDataParallel(
        model_vqvae,
        device_ids=[dist.get_local_rank()],
        output_device=dist.get_local_rank(),
    )
    
    
 
    
def get_quantizes_indices_labels_imgname(data_loader, tag):
    all_indices = []
    all_quantizes = []
    all_labels = []
    all_img_names = []  # <-- NEW: keep filenames aligned with quant/indices

    with torch.no_grad():
        for j, (images, labels) in tqdm(
            enumerate(data_loader),
            desc='Recall trained model to save codebook indices',
            leave=False
        ):
            # Get this batch's file paths IN THE SAME ORDER as 'images' in this batch.
            # This slicing assumes no shuffle; if shuffled, return path from __getitem__ instead.
            batch_paths = data_loader.dataset.image_files[
                j * data_loader.batch_size : (j + 1) * data_loader.batch_size
            ]
            # If you prefer basenames, use:
            # batch_names = [os.path.basename(p) for p in batch_paths]
            # Otherwise, keep full paths (recommended to avoid collisions):
            batch_names = list(batch_paths)

            images = images.float().to(device)
            quant_b, _, id_b, _, _ = model_vqvae.encode(images)
            outputs = model_vqvae.decode(quant_b)

            # Record filenames for this batch (must be same length as batch size)
            all_img_names.extend(batch_names)  # <-- NEW

            # (your optional visualization block)
            for idx, (label, out, img_path) in enumerate(zip(labels, outputs, batch_names)):
                if idx % 10000 == 0 or idx == 0:
                    save_file = os.path.join(
                        args.save_path_imgs,
                        f"{os.path.splitext(os.path.basename(img_path))[0]}_{label.item()}.png"
                    )
                    orig = images[idx]
                    grid = torch.stack([orig.detach().cpu(), out.detach().cpu()], dim=0)
                    grid_01 = (grid.clamp(-1, 1) + 1) / 2.0
                    utils.save_image(grid_01, save_file, nrow=2)

            all_indices.append(id_b.cpu())
            all_quantizes.append(quant_b.cpu())
            all_labels.extend(labels.cpu().numpy())

    # Concatenate & save
    indices_tensor   = torch.cat(all_indices, dim=0)
    quantizes_tensor = torch.cat(all_quantizes, dim=0)
    all_labels       = np.array(all_labels)

    # sanity check: lengths must match
    assert indices_tensor.shape[0] == quantizes_tensor.shape[0] == len(all_img_names), \
        f"Length mismatch: indices={indices_tensor.shape[0]}, quant={quantizes_tensor.shape[0]}, names={len(all_img_names)}"

    indices_path   = os.path.join(args.save_path_models, f"indices_epoch{epoch}_flat_vqvae80x80_144x456codebook_fullTrain_{tag}.npy")
    quantized_path = os.path.join(args.save_path_models, f"quantized_epoch{epoch}_flat_vqvae80x80_144x456codebook_fullTrain_{tag}.npy")
    labels_path    = os.path.join(args.save_path_models, f"labels_epoch{epoch}_flat_vqvae80x80_144x456codebook_fullTrain_{tag}.npy")
    names_path     = os.path.join(args.save_path_models, f"filenames_epoch{epoch}_flat_vqvae80x80_144x456codebook_fullTrain_{tag}.npy")  # <-- NEW

    np.save(indices_path,   indices_tensor.numpy())
    np.save(quantized_path, quantizes_tensor.numpy())
    np.save(labels_path,    all_labels)
    np.save(names_path,     np.array(all_img_names, dtype=object))
    
    
    

if args.train_vqvae:
    os.makedirs(args.save_path_models, exist_ok=True)
    get_quantizes_indices_labels_imgname(data_loader, 'train')
    get_quantizes_indices_labels_imgname(data_loader, 'val')    
# =============================================================================
#     model_vqvae.eval()
#     all_indices = []
#     all_quantizes = []
#     all_labels = []
#     all_img_names = []  # <-- NEW: keep filenames aligned with quant/indices
# 
#     all_indices_val = []
#     all_quantizes_val = []
#     all_labels_val = []
#     all_img_names_val = []
# 
#     with torch.no_grad():
#         for j, (images, labels) in tqdm(
#             enumerate(data_loader),
#             desc='Recall trained model to save codebook indices',
#             leave=False
#         ):
#             # Get this batch's file paths IN THE SAME ORDER as 'images' in this batch.
#             # This slicing assumes no shuffle; if shuffled, return path from __getitem__ instead.
#             batch_paths = data_loader.dataset.image_files[
#                 j * data_loader.batch_size : (j + 1) * data_loader.batch_size
#             ]
#             # If you prefer basenames, use:
#             # batch_names = [os.path.basename(p) for p in batch_paths]
#             # Otherwise, keep full paths (recommended to avoid collisions):
#             batch_names = list(batch_paths)
# 
#             images = images.float().to(device)
#             quant_b, _, id_b, _, _ = model_vqvae.encode(images)
#             outputs = model_vqvae.decode(quant_b)
# 
#             # Record filenames for this batch (must be same length as batch size)
#             all_img_names.extend(batch_names)  # <-- NEW
# 
#             # (your optional visualization block)
#             for idx, (label, out, img_path) in enumerate(zip(labels, outputs, batch_names)):
#                 if idx % 10000 == 0 or idx == 0:
#                     save_file = os.path.join(
#                         args.save_path_imgs,
#                         f"{os.path.splitext(os.path.basename(img_path))[0]}_{label.item()}.png"
#                     )
#                     orig = images[idx]
#                     grid = torch.stack([orig.detach().cpu(), out.detach().cpu()], dim=0)
#                     grid_01 = (grid.clamp(-1, 1) + 1) / 2.0
#                     utils.save_image(grid_01, save_file, nrow=2)
# 
#             all_indices.append(id_b.cpu())
#             all_quantizes.append(quant_b.cpu())
#             all_labels.extend(labels.cpu().numpy())
# 
#     # Concatenate & save
#     indices_tensor   = torch.cat(all_indices, dim=0)
#     quantizes_tensor = torch.cat(all_quantizes, dim=0)
#     all_labels       = np.array(all_labels)
# 
#     # sanity check: lengths must match
#     assert indices_tensor.shape[0] == quantizes_tensor.shape[0] == len(all_img_names), \
#         f"Length mismatch: indices={indices_tensor.shape[0]}, quant={quantizes_tensor.shape[0]}, names={len(all_img_names)}"
# 
#     indices_path   = os.path.join(args.save_path_models, f"indices_epoch{epoch}_flat_vqvae80x80_144x456codebook_fullTrain.npy")
#     quantized_path = os.path.join(args.save_path_models, f"quantized_epoch{epoch}_flat_vqvae80x80_144x456codebook_fullTrain.npy")
#     labels_path    = os.path.join(args.save_path_models, f"labels_epoch{epoch}_flat_vqvae80x80_144x456codebook_fullTrain.npy")
#     names_path     = os.path.join(args.save_path_models, f"filenames_epoch{epoch}_flat_vqvae80x80_144x456codebook_fullTrain.npy")  # <-- NEW
# 
#     np.save(indices_path,   indices_tensor.numpy())
#     np.save(quantized_path, quantizes_tensor.numpy())
#     np.save(labels_path,    all_labels)
#     np.save(names_path,     np.array(all_img_names, dtype=object))  # <-- NEW
# =============================================================================
    


"""# Train a Classifier"""

class ReconstructedDataset(Dataset):
    def __init__(self, images, labels, transform=None):
        self.images = images
        self.labels = labels
        self.transform = transform 

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        image = self.images[idx]
        label = self.labels[idx]
        if self.transform:
            image = self.transform(image)
        return image, label



def decode_quantizes(model, quantizes, batch_size=32, device="cuda"):
    """
    Decode quantized latent codes into images in batches to avoid CUDA OOM.
    Args:
        model: trained VQ-VAE model
        quantizes: numpy array [N, C, H, W] or tensor [N, C, H, W]
        batch_size: how many samples to decode per batch
        device: "cuda" or "cpu"
    Returns:
        images: concatenated tensor [N, C, H, W]
    """
    # 🔹 Debug info once
    if isinstance(quantizes, np.ndarray):
        print(f"[decode_quantizes] quantizes is numpy array, shape={quantizes.shape}, dtype={quantizes.dtype}")
    elif torch.is_tensor(quantizes):
        print(f"[decode_quantizes] quantizes is torch tensor, shape={tuple(quantizes.shape)}, dtype={quantizes.dtype}")
    else:
        raise TypeError(f"quantizes must be numpy.ndarray or torch.Tensor, got {type(quantizes)}")

    model.eval()
    images = []
    with torch.no_grad():
        for i in range(0, len(quantizes), batch_size):
            batch = quantizes[i:i+batch_size]
            if isinstance(batch, np.ndarray):  # convert numpy → tensor if needed
                batch = torch.from_numpy(batch).float()
            batch = batch.to(device, non_blocking=True)

            out = model.decode(batch)
            images.append(out.cpu())

            del batch, out
            torch.cuda.empty_cache()

    return torch.cat(images, dim=0)



ckpt_vqvae = "/local/altamabp/checkpoint/vqvae/model_epoch100_flat_vqvae80x80_144x456codebook_fullTrain.pth"
torch.cuda.set_device(3) 
torch.cuda.empty_cache()
device = "cuda" if torch.cuda.is_available() else "cpu"

quantizes = np.load('/local/altamabp/checkpoint/vqvae/quantized_epoch100_flat_vqvae80x80_144x456codebook_fullTrain_train.npy')
labels = np.load('/local/altamabp/checkpoint/vqvae/labels_epoch100_flat_vqvae80x80_144x456codebook_fullTrain_train.npy')
labels = torch.from_numpy(labels)

model_vqvae = FlatVQVAE().to(device)
model_vqvae.load_state_dict(torch.load(ckpt_vqvae, map_location=device))
model_vqvae = model_vqvae.to(device)
model_vqvae.eval()

reconstructed_images = decode_quantizes(model_vqvae, quantizes, batch_size=32, device=device)


from torchvision.transforms import v2 as T
import torch

recon_transform = T.Compose([
    T.Resize((80, 80)),
    T.ToImage(),                              # accepts PIL or tensor
    T.ToDtype(torch.float32, scale=True),     # scales uint8 to [0,1]
])
# =============================================================================
# recon_transform = transforms.Compose([
#     transforms.Resize((80,80)),
#     transforms.Normalize([0.5, 0.5, 0.5], [0.5, 0.5, 0.5]),
# ])
# =============================================================================


#Incase training the classifier on reconstructed VQVAE images rather than the originals, labels are the original labels
#dataset = ReconstructedDataset(reconstructed_images, labels, transform=recon_transform) #normalizing again causes oversclaing. But-> Make sure that the recons are already [-1,1]
#data_loader_reconstructions = DataLoader(dataset, batch_size=16, shuffle=False, num_workers=0) # still only works when you set the num_worker to 0?

# =============================================================================
# for inputs, labels in data_loader_reconstructions:
#     print('reconstructions inputs.shape: ', inputs.shape)
#     print('reconstructions labels.shape: ', labels.shape)
#     break
# =============================================================================

from torch.utils.data import DataLoader
import torch.optim as optim
import torch.nn as nn
from torchvision import transforms

# Transforms (same as your pipeline)
transform = transforms.Compose([
    transforms.Resize((80,80)),
    transforms.ToTensor(),
#    transforms.Normalize([0.5, 0.5, 0.5], [0.5, 0.5, 0.5]),
])

# Dataset + DataLoader
train_loader = DataLoader(dataset, batch_size=32, shuffle=False, num_workers=4)

# Loss + Optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(), lr=0.001, momentum=0.9)


#val_dataset = datasets.ImageFolder("UTKFace_dataset_test_structured", transform=transform)
val_loader = DataLoader(dataset_val, batch_size=32, shuffle=False, num_workers=4)


# --------------------------
# Classifier (ResNet50)
# --------------------------
classifier = resnet50(weights=None)
classifier.fc = nn.Linear(classifier.fc.in_features, 10)  
classifier.to(device)

nn.init.normal_(classifier.fc.weight, mean=0.0, std=0.01)
nn.init.zeros_(classifier.fc.bias)


def _epoch_loop(loader, model, criterion, device, optimizer=None, desc=""):
    """
    One pass over `loader`. If `optimizer` is provided -> training, else validation.
    Returns (loss_avg, acc_pct).
    """
    is_train = optimizer is not None
    model.train() if is_train else model.eval()

    loss_sum, correct, total = 0.0, 0, 0
    pbar = tqdm(loader, desc=desc, unit="batch")

    for inputs, labels in pbar:
        inputs, labels = inputs.to(device), labels.to(device)

        if is_train:
            optimizer.zero_grad(set_to_none=True)

        with torch.set_grad_enabled(is_train):
            outputs = classifier(inputs)
            loss = criterion(outputs, labels)
            if is_train:
                loss.backward()
                optimizer.step()

        # accumulate using sample-weighted loss (robust to last batch size)
        bs = labels.size(0)
        loss_sum += loss.item() * bs
        _, predicted = torch.max(outputs, 1)
        total += bs
        correct += (predicted == labels).sum().item()

        # live progress shows running averages
        run_loss = loss_sum / max(1, total)
        run_acc = 100.0 * correct / max(1, total)
        pbar.set_postfix({"loss": f"{run_loss:.4f}", "acc": f"{run_acc:.2f}%"})

    epoch_loss = loss_sum / max(1, total)
    epoch_acc = 100.0 * correct / max(1, total)
    return epoch_loss, epoch_acc

if args.train_classifier:
    print("Training classifier...")
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.SGD(classifier.parameters(), lr=0.001, momentum=0.9)

    num_epochs = 100  # change as needed
    for epoch in range(num_epochs):
        # ---- Train (one pass) ----
        train_loss, train_acc = _epoch_loop(
            train_loader, classifier, criterion, device,
            optimizer=optimizer,
            desc=f"[Train] Epoch {epoch+1}/{num_epochs}"
        )

        # ---- Validate (one pass) ----
        val_loss, val_acc = _epoch_loop(
            val_loader, classifier, criterion, device,
            optimizer=None,
            desc=f"[Val]   Epoch {epoch+1}/{num_epochs}"
        )

        # ---- Logging (per epoch) ----
        if "run" in globals() and run is not None:
            try:
                run["classifier/train-loss"].log(train_loss, step=epoch + 1)
                run["classifier/train-acc"].log(train_acc, step=epoch + 1)
                run["classifier/lr"].log(optimizer.param_groups[0]["lr"], step=epoch + 1)

                run["classifier/val-loss"].log(val_loss, step=epoch + 1)
                run["classifier/val-acc"].log(val_acc, step=epoch + 1)
            except Exception:
                pass

        print(
            f"[Classifier] Epoch {epoch+1}/{num_epochs} -- "
            f"Train Loss={train_loss:.4f}, Train Acc={train_acc:.2f}% "
            f"-- Val Loss={val_loss:.4f}, Val Acc={val_acc:.2f}%"
        )

        # Save checkpoint (optional)
        torch.save(
            classifier.state_dict(),
            f"/local/altamabp/checkpoint/classifier/resnet50/weights_epoch{str(epoch+1).zfill(2)}_fullTrain.pth"
        )

else:
    print(f"Loading classifier from {args.classifier_ckpt}")
    classifier.load_state_dict(torch.load(args.classifier_ckpt, map_location=device))
    classifier.eval()


"""# Train Transformer"""

# =============================================================================
# run = neptune.init_run(
#     project="UTKFaces",
#     api_token="eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmUuYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS5haSIsImFwaV9rZXkiOiIwMmExYTliOC1mYjkyLTQ4M2YtYjFiYS1iZWQ1Y2E0OTJlNTkifQ==",
#     capture_stdout = False,
#     capture_stderr = False,
#     source_files=["pipeline_vqvae_transformer_classification.py"]
# )
# =============================================================================

# =============================================================================
# def train(epoch, loader, model, optimizer, scheduler, device, val_loader=None):
#     if is_primary():
#         loader = tqdm(loader)
#     model.train()
# 
#     loss = 0
#     i=0
#     for i, (input, label) in enumerate(loader):
# 
#         model.zero_grad()
#         input = input.to(device)
#         label = label.to(device)
# 
#         i = i+1
#         outputs = model(inputs_embeds = input,labels =label)
#         index = torch.argmax(outputs.logits, dim=2)
# 
#         loss, logits = outputs[:2]
# 
#         loss = loss.mean()
#         optimizer.zero_grad(set_to_none=True)
#         loss.backward()
#         optimizer.step()
#         if scheduler is not None:
#             scheduler.step()
# 
# 
#         if is_primary():
#             lr = optimizer.param_groups[0]["lr"]
# 
#             loader.set_description(
#                 (
#                     f"epoch: {epoch + 1}; loss: {loss:.5f}; "
#                     f"lr: {lr:.5f}"
#                 )
#             )
#         run["transformer/train-loss"].log(loss)
#         run["transformer/lr"].log(lr)
# 
# 
#     ##validation
#     if val_loader is not None:
#         if is_primary():
#             val_loader = tqdm(val_loader)
#             model.eval()
#         average_loss = 0
#         val_loss = 0
#         i=0
#         j=0
#         for i, (input, label) in enumerate(val_loader):
# 
#             if(i%500 ==0):
#                 j = j+1
#                 #model.zero_grad()
#                 #torch.no_grad()
#                 input = input.to(device)
#                 label = label.to(device)
# 
# 
#                 outputs = model(inputs_embeds = input,labels =label)
#                 val_loss, _ = outputs[:2]
#                 val_loss = val_loss.mean()
#                 run["transformer/val-loss"].log(val_loss)
#                 average_loss += val_loss
# 
#                 val_loader.set_description(
#                         (
#                             f"Validation loss: {val_loss:.5f} "
#                         )
#                     )
#         average_loss = average_loss/ j
#         run["transformer/val-average_loss_per_epoch"].log(average_loss)
#         return average_loss
# =============================================================================


import torch
from torch import nn


def train(
    epoch,
    loader,
    model,
    optimizer,
    scheduler,
    device,
    val_loader=None,
    num_classes=None,          # optional sanity check for C
    ignore_index=None,         # e.g., -100 if you have padding; else None
    log_every=500,             # how often to LOG (not compute) during val
    grad_clip_norm=None,       # e.g., 1.0 or None
    use_amp=True               # mixed precision on CUDA
):
    """
    inputs:  [B, 400, 74]  (64-d masked vec + 10-d one-hot -> 74)
    labels:  [B, 400]      (class indices in [0..C-1], or ignore_index for padding)
    logits:  [B, 400, C]   (model output)
    """

    # ---- set up ----
    # CE across tokens; ignore padded positions if ignore_index is provided
    criterion = nn.CrossEntropyLoss(ignore_index=ignore_index) if ignore_index is not None else nn.CrossEntropyLoss()

    scaler = torch.cuda.amp.GradScaler(enabled=(use_amp and device.type == "cuda"))

    # ---------- TRAIN ----------
    iterator = tqdm(loader) if is_primary() else loader
    model.train()  # ALL ranks

    for step, (inputs74, labels) in enumerate(iterator, start=1):
        # Move to device
        inputs74 = inputs74.to(device, non_blocking=True)      # [B, 400, 74]
        labels   = labels.to(device, non_blocking=True)        # [B, 400], dtype long

        # Attention mask: if you have padding/ignored positions -> mask valid tokens
        if ignore_index is not None:
            attention_mask = (labels != ignore_index).long()   # [B, 400]
        else:
            attention_mask = torch.ones_like(labels, dtype=torch.long, device=device)

        optimizer.zero_grad(set_to_none=True)

        # Forward (AMP optional)
        with torch.cuda.amp.autocast(enabled=(use_amp and device.type == "cuda")):
            logits = model(inputs_embeds=inputs74, attention_mask=attention_mask)  # [B, 400, C]

            # Sanity checks (lightweight; you can disable after debugging)
            if logits.dim() != 3:
                raise ValueError(f"Expected logits [B, T, C], got shape {tuple(logits.shape)}")
            B, T, C = logits.shape
            if num_classes is not None and C != num_classes:
                raise ValueError(f"Class count mismatch: logits C={C}, expected {num_classes}")
            if labels.shape != (B, T):
                raise ValueError(f"Labels shape {tuple(labels.shape)} must match [B, T] = ({B}, {T})")

            # Token CE: flatten ([B*T, C], [B*T])
            loss = criterion(logits.view(B * T, C), labels.view(B * T))

        # Backward
        if scaler.is_enabled():
            scaler.scale(loss).backward()
            if grad_clip_norm is not None:
                scaler.unscale_(optimizer)
                torch.nn.utils.clip_grad_norm_(model.parameters(), grad_clip_norm)
            scaler.step(optimizer)
            scaler.update()
        else:
            loss.backward()
            if grad_clip_norm is not None:
                torch.nn.utils.clip_grad_norm_(model.parameters(), grad_clip_norm)
            optimizer.step()

        if scheduler is not None:
            scheduler.step()

        # Logging (primary only)
        if is_primary():
            lr = optimizer.param_groups[0]["lr"]
            iterator.set_description(f"epoch: {epoch+1}; loss: {loss.item():.5f}; lr: {lr:.6f}")
            run["transformer/train-loss"].log(loss.item())
            run["transformer/lr"].log(lr)

    # ---------- VALIDATION ----------
    if val_loader is None:
        return None

    val_iter = tqdm(val_loader) if is_primary() else val_loader
    model.eval()  # ALL ranks

    total_loss = 0.0
    total_batches = 0

    with torch.no_grad():
        for vi, (inputs74, labels) in enumerate(val_iter, start=1):
            inputs74 = inputs74.to(device, non_blocking=True)
            labels   = labels.to(device, non_blocking=True)

            if ignore_index is not None:
                attention_mask = (labels != ignore_index).long()
            else:
                attention_mask = torch.ones_like(labels, dtype=torch.long, device=device)

            with torch.cuda.amp.autocast(enabled=(use_amp and device.type == "cuda")):
                logits = model(inputs_embeds=inputs74, attention_mask=attention_mask)  # [B, 400, C]
                B, T, C = logits.shape

                val_loss = criterion(logits.view(B * T, C), labels.view(B * T))

            total_loss += val_loss.item()
            total_batches += 1

            # Log progress every N batches (we still compute every batch for a true mean)
            if is_primary() and (vi % log_every == 0 or vi == 1):
                run["transformer/val-loss"].log(val_loss.item())
                if isinstance(val_iter, tqdm):
                    val_iter.set_description(f"Validation loss: {val_loss.item():.5f}")

    avg_val = total_loss / max(1, total_batches)
    if is_primary():
        run["transformer/val-average_loss_per_epoch"].log(avg_val)
    return avg_val



parser = argparse.ArgumentParser()
parser.add_argument("--n_gpu", type=int, default=1)

port = (
    2 ** 15
    + 2 ** 14
    + hash(os.getuid() if sys.platform != "win32" else 1) % 2 ** 14
)
parser.add_argument("--dist_url", default=f"tcp://127.0.0.1:{port}")

#parser.add_argument("--size", type=int, default=80)
parser.add_argument("--epoch", type=int, default=200)
parser.add_argument("--batch_size", type=int, default=16)
parser.add_argument("--lr", type=float, default=0.0001)
parser.add_argument("--sched", type=str, default="linearW")

parser.add_argument(
    "--ckpt_distil_combined",
    type=str,
    default="/local/altamabp/checkpoint/distil/80x80_100ClassImagenet_flat_144x456codebook_75mask_epoch100_fullTrain.pt",
    help="Path to combined distillation checkpoint"
)
parser.add_argument(
    "--ckpt_vqvae",
    type=str,
    default="/local/altamabp/checkpoint/vqvae/model_epoch100_flat_vqvae80x80_144x456codebook_fullTrain.pth",
    help="Path to trained VQ-VAE checkpoint"
)

parser.add_argument("--train_vqvae", action="store_true", help="Train VQ-VAE instead of loading checkpoint")
parser.add_argument("--train_classifier", action="store_true", help="Train classifier instead of loading checkpoint")
parser.add_argument("--train_transformer", action="store_true", help="Train transformer instead of loading checkpoint")

parser.add_argument("--classifier_ckpt", type=str, default="/local/altamabp/checkpoint/classifier/resnet50/weights_epoch100_fullTrain.pth", help="Path to classifier checkpoint")


parser.add_argument("--continue_train_transformer", action="store_true",
                    help="Resume transformer training for --epoch more epochs.")
parser.add_argument("--resume_transformer_path", type=str, default="",
                    help="Optional explicit transformer checkpoint path (.pt). If empty, picks latest from /local/altamabp/checkpoint/distil/")


args, unknown = parser.parse_known_args()


torch.cuda.set_device(3)  # Set default CUDA device to 3
torch.cuda.empty_cache()
device = torch.device("cuda:3" if torch.cuda.is_available() else "cpu")

#args.distributed = dist.get_world_size() > 1

# SAFE distributed flag (won’t throw if not initialized)
args.distributed = ddp_ready() and (dist.get_world_size() > 1)

#### train set###
train_labels = np.load('/local/altamabp/checkpoint/vqvae/labels_epoch100_flat_vqvae80x80_144x456codebook_fullTrain_train.npy')

train_indices = np.load('/local/altamabp/checkpoint/vqvae/indices_epoch100_flat_vqvae80x80_144x456codebook_fullTrain_train.npy')
n, h, w = train_indices.shape # 150000x400
train_indices = train_indices.reshape(n, h * w)

train_quantizes = np.load('/local/altamabp/checkpoint/vqvae/quantized_epoch100_flat_vqvae80x80_144x456codebook_fullTrain_train.npy')
n, c, h, w = train_quantizes.shape
train_quantizes = train_quantizes.transpose(0, 2, 3, 1)
train_quantizes = train_quantizes.reshape(n, h * w, c) # 150000X400X64

n_train_samples = train_quantizes.shape[0]
d_embed_vec = train_quantizes.shape[2]
n_tokens = train_quantizes.shape[1]

mask_token = 0
#mask_token_label = -100
mask_perc = 0.3#0.75
mask_train = np.random.default_rng().choice([True, False], size=(n_train_samples, n_tokens), p=[mask_perc, 1 - mask_perc])
train_quantizes = train_quantizes.reshape((n_train_samples, n_tokens, d_embed_vec))
train_indices = train_indices.reshape((n_train_samples, n_tokens))
#train_quantizes[mask_train] = mask_token
#masked_train_indices = np.copy(train_indices)
#masked_train_indices[mask_train] = mask_token

train_q = train_quantizes.float()                      # torch tensor #code breaks here
mins = train_q.amin(dim=(0,1))                        # (64,)
maxs = train_q.amax(dim=(0,1))                        # (64,)
scale = (maxs - mins).clamp_min(1e-6)                 # avoid divide-by-zero

class MinMax01:
    def __init__(self, mins, scale):
        self.mins  = mins.view(1,1,-1)
        self.scale = scale.view(1,1,-1)
    def __call__(self, x):                            # x: (N,400,64) or (400,64)
        return (x - self.mins.to(x.device)) / self.scale.to(x.device)

train_quantizes_normalized = transforms.Compose([
    MinMax01(mins, scale),                            # -> [0,1]
])

masked_train_quantizes = np.copy(train_quantizes_normalized)
masked_train_quantizes[mask_train] = mask_token 

train_indices_label = np.copy(train_labels)
#train_indices_label[~mask_train] = mask_token_label
masked_train_quantizes = torch.from_numpy(masked_train_quantizes)
#masked_train_indices = torch.from_numpy(masked_train_indices)
train_indices_label = torch.from_numpy(train_indices_label)


N, T = train_indices.shape
num_classes = 10




# 1) One-hot encode labels → (N, T, 10)
#    Make sure dtype is long and device matches the quantizes tensor.
idx = train_indices_label.to(dtype=torch.long, device=masked_train_quantizes.device)



one_hot_labels = torch.nn.functional.one_hot(idx, num_classes=num_classes)           # int tensor (N, T, 10)
one_hot_labels = one_hot_labels.to(dtype=masked_train_quantizes.dtype)    # match float dtype for concat
one_hot_labels_3d = one_hot_labels.unsqueeze(1).expand(-1, T, -1)

# 2) Concatenate along feature dim → (N, T, 64 + 10) = (N, T, 74)
masked_exp_train_quantizes = torch.cat([one_hot_labels_3d, masked_train_quantizes], dim=2)

print('masked_exp_train_quantizes.shape',masked_exp_train_quantizes.shape)  # torch.Size([160000, 400, 74])




indices = set(train_indices.flatten())
indices = sorted(indices)
vocab_size = indices[-1] + 1

print('indices: ', indices)
print('indices max: ', max(indices))
print('indices min: ', min(indices))


# added during UTKFace debugging
train_indices_label = train_indices_label.to(device).long()  # enforce int64


# --- Transformer train/val split (10%) ---
n_total = train_quantizes.shape[0]
idx_all = np.arange(n_total)
tr_idx, val_idx = train_test_split(
    idx_all, test_size=0.10, random_state=42, shuffle=False
)

x_tr  = masked_exp_train_quantizes[tr_idx] #masked_train_quantizes[tr_idx] #train_quantizes[tr_idx]
y_tr  = train_indices[tr_idx]
x_val = masked_exp_train_quantizes[val_idx] #masked_train_quantizes[val_idx] #train_quantizes[val_idx]
y_val = train_indices[val_idx]

train_data = ReconstructedDataset(x_tr,  y_tr)#(x_tr[0, None],  y_tr[0, None])
val_data   = ReconstructedDataset(x_val, y_val)#(x_val[0, None], y_val[0, None])

train_dataloader = DataLoader(train_data, batch_size=args.batch_size, shuffle=False) #, num_workers=12
val_dataloader   = DataLoader(val_data,   batch_size=args.batch_size, shuffle=False)

cfg = DistilBertConfig(
    vocab_size=vocab_size,
    hidden_size=74,#d_embed_vec,
    sinusoidal_pos_embds=False,
    n_layers=6,
    n_heads=2,#4,
    max_position_embeddings=n_tokens
)

model = DistilBertForMaskedLM(cfg)
# model.load_state_dict(torch.load(args.ckpt_distil))

# DataParallel: use device_ids=[3] because you want to use GPU 3
model = torch.nn.DataParallel(model, device_ids=[3], output_device=3)
model = model.to(device)

if args.distributed:
    model = nn.parallel.DistributedDataParallel(
        model,
        device_ids=[3],
        output_device=3,
    )

optimizer = torch.optim.AdamW(model.parameters(), lr=args.lr, weight_decay=0.005)
scheduler = None
if args.sched == "linearW":
    scheduler = torch.optim.lr_scheduler.OneCycleLR(
        optimizer,
        max_lr=0.0006,
        pct_start=0.01,
        steps_per_epoch=len(train_dataloader),
        epochs=args.epoch,
        anneal_strategy='linear'
    )

# Training loop
if args.train_transformer:
    j = 0
    min_validation_loss = np.inf
    for i in range(args.epoch):
        j += 1
        print(len(train_dataloader))
        train(i, train_dataloader, model, optimizer, scheduler, device, val_dataloader)
        torch.cuda.empty_cache()
        run["transformer/train-epoch"].log(j)
        if is_primary():
            if isinstance(model, torch.nn.DataParallel):
                model = model.module
            torch.save(model.state_dict(), f"/local/altamabp/checkpoint/distil/80x80_100ClassImagenet_flat_144x456codebook_75mask_epoch{str(j).zfill(3)}.pt")

"""# Run Masking-Transformer-VQVAE"""

# =============================================================================
# run = neptune.init_run(
#     project="UTKFaces",
#     api_token="eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmUuYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS5haSIsImFwaV9rZXkiOiIwMmExYTliOC1mYjkyLTQ4M2YtYjFiYS1iZWQ1Y2E0OTJlNTkifQ==",
#     capture_stdout = False,
#     capture_stderr = False,
#     # with_id="MAS-389"
#     source_files=["pipeline_vqvae_transformer_classification.py"]
# )
# =============================================================================
# =============================================================================
# 
# def random_mask(unmasked, indices_unmasked,n_sample, n_token, mask_perc):
# 
#     #mask = np.random.default_rng().choice([True, False], size=(1,n_token, 1), p=[mask_perc, 1 - mask_perc])
#     
#     masked = unmasked.clone()
#     device = masked.device 
#     token_mask = (torch.rand((1, 400, 1), device=device) < mask_perc)  
#     #masked[mask] = 0  # Assuming 0 is the mask token
#     masked = masked.masked_fill(token_mask, 0.0)
# 
#     m = token_mask
#     if m.ndim > 1:
#         m = m.squeeze()          # collapse to (400,)
#     m = m.to(dtype=torch.bool)    # ensure bool
#     assert m.shape == indices_unmasked.shape
#     
#     
#     indices_masked = indices_unmasked.clone()
#     #indices_masked[~mask[0]] = -100 # Assuming -100 is the mask label token
#     indices_masked[m]=0
# 
#     return masked, indices_masked, token_mask#[0][0]
# 
# =============================================================================



def random_mask(unmasked, indices_unmasked, n_sample, n_token, mask_perc):
    # Boolean mask [n_token]
    mask = (torch.rand((n_token,), device=unmasked.device) < mask_perc)  # shape [n_token]

    masked = unmasked.clone()
    masked[:, mask, :] = 0  # zero out embeddings for masked tokens

    indices_masked = indices_unmasked.clone()
    indices_masked[mask] = 0#-100  # set masked tokens to -100

    return masked, indices_masked, mask


indices = np.load('/local/altamabp/checkpoint/vqvae/indices_epoch100_flat_vqvae80x80_144x456codebook_fullTrain_val.npy')
n, h, w = indices.shape
indices = indices.reshape(n, h * w)

quantizes = np.load('/local/altamabp/checkpoint/vqvae/quantized_epoch100_flat_vqvae80x80_144x456codebook_fullTrain_val.npy')
quant_b = quantizes
n, c, h, w = quantizes.shape
quantizes = quantizes.transpose(0, 2, 3, 1)
quantizes = quantizes.reshape(n, h * w, c)

#Bottom data and parameters
n_sample = quantizes.shape[0]
d_embed_vec = quantizes.shape[2]
n_token = np.prod(quantizes.shape[1])
quantizes = quantizes.reshape((n_sample, n_token, d_embed_vec))
length = int(math.sqrt(n_token))
indices = indices.reshape((n_sample, n_token))
indices_to_sort = set(indices.flatten())
indices_to_sort = sorted(indices_to_sort)
vocab_size = indices_to_sort[-1] + 1

#Define Distilbert model
cfg = DistilBertConfig(
        vocab_size=vocab_size,
        hidden_size=d_embed_vec,
        sinusoidal_pos_embds=False,
        n_layers=6,
        n_heads=4,
        max_position_embeddings=n_token
)
model_distil = DistilBertForMaskedLM(cfg).to(device)
model_distil.load_state_dict(torch.load(args.ckpt_distil_combined))
model_distil = model_distil.to(device)
model_distil.eval()

#Define VQVAE model
model_vqvae = FlatVQVAE().to(device)
model_vqvae.load_state_dict(torch.load(args.ckpt_vqvae, map_location=device))
model_vqvae = model_vqvae.to(device)
model_vqvae.eval()

# Define classifier and load saved model(weights)
classifier = resnet50(weights=None)
classifier.fc = nn.Linear(classifier.fc.in_features, 10)
classifier.load_state_dict(torch.load('/local/altamabp/checkpoint/classifier/resnet50/weights_epoch100_fullTrain.pth'))
classifier.to(device)
classifier.eval()


mask_percentages = np.arange(0.1, 1.1, 0.1)
# mask_percentages = np.append(mask_percentages,[.85,.95])
mask_percentages = np.sort(mask_percentages)

average_errors = []

# Make sure save directory exists
save_dir = "image/image-reconstructed_fullTrain"
os.makedirs(save_dir, exist_ok=True)


import glob
from torchvision.transforms import functional as TF
from torchvision.transforms import InterpolationMode
from PIL import Image, ImageDraw, ImageFont

def resolve_image_path(name, roots):
    """
    Return a real file path for 'name'.
    - If 'name' is already an absolute/existing path, return it.
    - Else try each root: join(root, name).
    - Else search recursively by basename under each root.
    """
    name = str(name)
    # already a full, existing path?
    if os.path.isabs(name) and os.path.isfile(name):
        return name
    # try direct join with roots
    for r in roots:
        cand = os.path.join(r, name)
        if os.path.isfile(cand):
            return cand
    # fallback: search by basename
    base = os.path.basename(name)
    for r in roots:
        hits = glob.glob(os.path.join(r, "**", base), recursive=True)
        if hits:
            return hits[0]
    raise FileNotFoundError(f"Could not resolve image path for '{name}' under roots: {roots}")
    
    
def _tensor_to_pil(img_t: torch.Tensor) -> Image.Image:
    """img_t: [C,H,W] in [-1,1] or [0,1] -> PIL RGB"""
    t = img_t.detach().cpu().float()
    if t.min() < 0:  # assume [-1,1]
        t = (t.clamp(-1, 1) + 1) / 2.0
    else:            # assume [0,1]
        t = t.clamp(0, 1)
    t = (t * 255.0).round().byte()
    npimg = t.permute(1, 2, 0).numpy()  # HWC
    return Image.fromarray(npimg, mode="RGB")


def save_row_with_labels(tiles, labels, out_path, label_h=18, pad=2):
    """
    tiles: list of torch.Tensor [C,H,W], length N
    labels: list of str ('' to skip), length N
    Writes a single-row image with a label bar above each tile.
    """
    assert len(tiles) == len(labels)
    pil_tiles = [_tensor_to_pil(t) for t in tiles]
    w, h = pil_tiles[0].width, pil_tiles[0].height
    total_w = len(pil_tiles) * (w + pad) - pad
    total_h = h + label_h
    canvas = Image.new("RGB", (total_w, total_h), (0, 0, 0))
    draw = ImageDraw.Draw(canvas)
    try:
        font = ImageFont.load_default()
    except Exception:
        font = None

    x = 0
    for im, text in zip(pil_tiles, labels):
        # label background strip
        if text:
            draw.rectangle([x, 0, x + w, label_h], fill=(20, 20, 20))
            tw, th = draw.textsize(text, font=font) # textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
            draw.text((x + (w - tw)//2, (label_h - th)//2), text, fill=(255, 255, 255), font=font)
        # paste image under label bar
        canvas.paste(im, (x, label_h))
        x += w + pad
    canvas.save(out_path)



criterion = nn.MSELoss()
criterion_class = nn.CrossEntropyLoss()



# Rebuild the images list in the same order used when encoding:
# (this mirrors how 'batch_indices' was formed originally)
all_paths = data_loader.dataset.image_files              # full list in order
img_names = [os.path.basename(p) for p in all_paths]     # or keep full paths

# Now use img_names[x] exactly as above



#for x in range(quantizes.shape[0]):
for x in tqdm(range(quantizes.shape[0]), desc="Processing", unit="img"):
    #print(x)

    transformer_outputs = []

    q = torch.from_numpy(quantizes[x]).to(device)
    index = torch.from_numpy(indices[x]).to(device)
    q = q.reshape(1, q.size(0), q.size(1))

    # Decode original image
    vqvae_out = model_vqvae.decode(torch.from_numpy(quant_b[x]).to(device))

    # Decode masked once at 50% for visualization
    with torch.no_grad():
        q_masked, index_masked, mask = random_mask(q, index, n_sample, n_token, 0.5)
        index_masked_forvis = index.clone()
        index_masked_forvis[mask] = 0
        vqvae_masked_out = model_vqvae.decode_code(index_masked_forvis.reshape(1, length, length))

    # Classify original for naming
    vqvae_img = vqvae_out
    if vqvae_img.ndim == 3:            # (C,H,W) -> (1,C,H,W)
        vqvae_img = vqvae_img.unsqueeze(0)
    #vqvae_img = preprocess(vqvae_out.unsqueeze(0)).to(device) #(vqvae_out.clamp(-1, 1) + 1) / 2.0 # -> [0,1]
    vqvae_img_prob = classifier(vqvae_img) #classifier(preprocess(vqvae_img).unsqueeze(0).to(device))
    _, vqvae_img_label = torch.max(vqvae_img_prob, 1)

    # Loop over mask percentages
    for perc in mask_percentages:
        with torch.no_grad():
            q_masked, index_masked, mask = random_mask(q, index, n_sample, n_token, perc)
            q_masked = q_masked.to(device)
        
            outputs = model_distil(inputs_embeds=q_masked, output_hidden_states=True)
        
            # 1) argmax -> tokens
            pred_tokens = torch.argmax(outputs.logits, dim=2)[0].to(device).long()
        
            # 2) clamp to valid vocab (defensive)
            vmax = model_distil.config.vocab_size - 1
            pred_tokens.clamp_(0, vmax)
        
            # 3) copy original index grid, fill only masked positions, ensure long dtype
            confidence_based_recons_index = index.clone().long()
            confidence_based_recons_index[mask] = pred_tokens[mask]
            
            # Confirm shapes and dtypes before decoding
            assert confidence_based_recons_index.dtype == torch.long
            assert confidence_based_recons_index.shape == (n_token,)
        
            # 4) decode using LONG index grid of shape [1, H, W]
            distil_out = model_vqvae.decode_code(
                confidence_based_recons_index.reshape(1, length, length).long()
            )
        
            transformer_outputs.append(distil_out.squeeze(0).cpu())

# =============================================================================
#         with torch.no_grad():
#             q_masked, index_masked, mask = random_mask(q, index, n_sample, n_token, perc)
#             q_masked = q_masked.to(device)
# 
#             outputs = model_distil(inputs_embeds=q_masked, output_hidden_states=True)
#             pred_tokens = torch.argmax(outputs.logits, dim=2)[0].detach().to(device).long()
# 
#             confidence_based_recons_index = index.clone()
#             confidence_based_recons_index[mask] = pred_tokens[mask]
# 
#             distil_out = model_vqvae.decode_code(
#                 confidence_based_recons_index.reshape(1, length, length)
#             )
# 
#             transformer_outputs.append(distil_out.squeeze(0).cpu())
# 
# =============================================================================
            
            # Print the fraction of tokens predicted as 0. If too high, transformer needs more training /  lower mask rate.
            if perc in (0.5, 0.9):
                zero_frac = (pred_tokens == 0).float().mean().item()
                if zero_frac > 0.5 and is_primary():
                    print(f"[warn] perc={perc:.2f}: {zero_frac*100:.1f}% tokens predicted as 0")
    
    # If you saved full paths, this will just return immediately.
    # If you saved basenames, this will resolve them under your dataset roots.
    # --- resolve path (works for full paths or basenames) ---
    img_path = resolve_image_path(
        img_names[x],
        roots=[
            "/local/altamabp/UTKFace_dataset_subset_150000",
            "/local/altamabp/UTKFace_dataset_test_structured",
        ],
    )
    
    # --- load the image ---
    img = Image.open(img_path).convert("RGB")
    
    # --- target HW = VQ-VAE recon size (e.g., 80x80) ---
    target_hw = tuple(vqvae_out.shape[-2:])  # (H, W)
    
    # --- prefer dataset transform if present AND produces correct size; else fallback ---
    vq_tfm = getattr(dataset, "transform", None) or getattr(dataset_val, "transform", None)
    if vq_tfm is not None:
        img_t = TF.to_tensor(img)  
        probe = vq_tfm(img_t)
        if tuple(probe.shape[-2:]) == target_hw:
            orig = probe
        else:
            # dataset tf outputs wrong size (e.g., token grid 20x20) -> fallback to a single, correct resize
            img_rs = TF.resize(img, target_hw, interpolation=InterpolationMode.BICUBIC, antialias=True)
            orig = TF.to_tensor(img_rs)
            orig = TF.normalize(orig, [0.5, 0.5, 0.5], [0.5, 0.5, 0.5])  # -> [-1,1]
    else:
        # no dataset tf -> explicit resize + normalize once
        img_rs = TF.resize(img, target_hw, interpolation=InterpolationMode.BICUBIC, antialias=True)
        orig = TF.to_tensor(img_rs)
        orig = TF.normalize(orig, [0.5, 0.5, 0.5], [0.5, 0.5, 0.5])  # -> [-1,1]
    

    # --- build row: ORIGINAL | VQ-VAE RECON | MASKED | transformer recons ---
    row_images = [orig.cpu(),
                  vqvae_out.squeeze(0).cpu()] + transformer_outputs

    # Labels: no text for first two, show mask % for masked + transformer outputs
    masked_pct = 0.5  # this is the one you used above for vqvae_masked_out
    labels = ["Original", "VQVAE recon"] + [f"mask {int(p*100)}%" for p in mask_percentages]
    
    # Save only every 10,000th sample
    if x % 10000 == 0:
        print('max vqvae out: ', vqvae_out.max().item())
        print('min vqvae_out: ', vqvae_out.min().item())
        print('max orig: ', orig.max().item())
        print('min orig: ', orig.min().item())
        
        out_path = os.path.join(
            save_dir,
            f"80x80_random_{str(x).zfill(5)}_{vqvae_img_label.item()}.png"
        )
        save_row_with_labels(row_images, labels, out_path)  # <-- new saver with text
        print(f"Saved: {out_path}")


# =============================================================================
# transformer_outputs=[]
# for perc in mask_percentages:
#     reconstruction_errors = []
#     cross_entropy_class_err = []
# 
#     criterion = nn.MSELoss()
#     criterion_class = nn.CrossEntropyLoss()
#     correct_random_pred = 0
#     tot_sample = 0
#     for x in tqdm(range(quantizes.shape[0]), desc="Processing", unit="img"):#for x in range(0,quantizes.shape[0]):
#         #print(x)
#         q = torch.from_numpy(quantizes[x])
#         index = torch.from_numpy(indices[x])
#         index = index.to(device)
#         q = q.to(device)
#         q = torch.reshape(q, (1, q.size(dim=0), q.size(dim=1)))
# 
#         with torch.no_grad():
#             q_masked, index_masked, mask = random_mask(q, index , n_sample, n_token,perc)
#             q_masked = q_masked.to(device)
#             index_masked = index_masked.to(device)            
# 
#         #Fill in predicted tokens
#         with torch.no_grad():
#             outputs = model_distil(inputs_embeds = q_masked, output_hidden_states = True)
#             confidence_based_prediction = torch.argmax(outputs.logits, dim=2)
#             confidence_based_prediction= confidence_based_prediction.reshape(n_tokens)
#             confidence_based_recons_index = index
#             #print(mask.shape)
#             for p in range(0,n_token):
#                 if(mask[0][p].any()):
#                     #confidence_based_recons_index[p] = confidence_based_prediction.detach().cpu().numpy()[0][p]
#                     confidence_based_recons_index[p] = confidence_based_prediction[p]#[0][p]
# 
#             #Reconstruct with distil predictions
#             confidence_based_recons_index = confidence_based_recons_index.to(device)
#             distil_out = model_vqvae.decode_code(torch.reshape(confidence_based_recons_index, (1,length,length)).to(device))
# 
#             #Reconstruct Original
#             vqvae_out = model_vqvae.decode(torch.from_numpy(quant_b[x]).to(device)) #torch.reshape(torch.from_numpy(indices[x]), (1,length,length)).to(device)
#             #index_masked_forvis = index.clone()
#             #index_masked_forvis[mask]=0
#             vqvae_masked_out = model_vqvae.decode_code(torch.reshape(index_masked, (1,length,length)).to(device))
# 
#             # Label outputs
#             vqvae_out = vqvae_out.unsqueeze(0)
#             vqvae_img = transforms.functional.normalize(vqvae_out, [0.5, 0.5, 0.5], [0.5, 0.5, 0.5])
#             vqvae_img = vqvae_img.to(device)
#             vqvae_img_prob = classifier(vqvae_img)
#             _, vqvae_img_label = torch.max(vqvae_img_prob, 1)
# 
#             rand_mask_img = transforms.functional.normalize(distil_out, [0.5, 0.5, 0.5], [0.5, 0.5, 0.5])
#             rand_mask_img = rand_mask_img.to(device)
#             rand_mask_img_prob = classifier(rand_mask_img)
#             _, rand_mask_img_label = torch.max(rand_mask_img_prob, 1)
#             correct_random_pred += (rand_mask_img_label == vqvae_img_label).sum().item()
# 
#             tot_sample += 1
#             #print(tot_sample)
# 
# 
#             if x%10000 ==0:
#                 print(f'rand_mask_img_label is {rand_mask_img_label}')
#                 print(f'vqvae_img_label is {vqvae_img_label}')
#                 print(f'rand_mask_img_label is {rand_mask_img_label.item()}')
#                 print(f'vqvae_img_label is {vqvae_img_label.item()}')
#                 print(f'correct_random_pred is {correct_random_pred}')
#                 
#                 utils.save_image(
#                     torch.cat([vqvae_out, vqvae_masked_out, distil_out], 0).to(device),
#                     f"image/mask-reconstructed/80x80_random_{vqvae_img_label.item()}_{rand_mask_img_label.item()}_{int(perc*100)}_{str(x).zfill(5)}.png",
#                     nrow=3,
#                     normalize=True,
#                     value_range=(-1, 1),
#                 )
# 
#         recon_loss = criterion(distil_out, vqvae_out)
#         run["recons/mse_per_image_random_mask"].log(recon_loss.item())
#         reconstruction_errors.append(recon_loss.item())
#         class_loss = criterion_class(rand_mask_img_prob, vqvae_img_prob)
#         run["recons/cross_entropy_per_image_random_mask"].log(class_loss.item())
#         cross_entropy_class_err.append(class_loss.item())
#     run["recons/average_mse_per_precision_random_mask"].log(np.mean(reconstruction_errors))
#     run["recons/average_cross_entropy_error_random_mask"].log(np.mean(cross_entropy_class_err))
#     average_errors.append(np.mean(reconstruction_errors))
#     pred_acc_random_mask = correct_random_pred/tot_sample
#     pred_err_random_mask = 1-pred_acc_random_mask
#     run["recons/average_classification_accuracy_random"].log(pred_err_random_mask)
# =============================================================================
